export const data = [
  {
    id: 1,
    question: 'What is the capital of France?',
    option1: 'Berlin',
    option2: 'Madrid',
    option3: 'Paris',
    option4: 'Rome',
    answer: 'Paris',
  },
  {
    id: 2,
    question: 'What is the largest planet in our solar system?',
    option1: 'Earth',
    option2: 'Jupiter',
    option3: 'Mars',
    option4: 'Saturn',
    answer: 'Jupiter',
  },
  {
    id: 3,
    question: "Which element has the chemical symbol 'O'?",
    option1: 'Oxygen',
    option2: 'Osmium',
    option3: 'Gold',
    option4: 'Iron',
    answer: 'Oxygen',
  },
  {
    id: 4,
    question: "Who wrote 'Romeo and Juliet'?",
    option1: 'Mark Twain',
    option2: 'Charles Dickens',
    option3: 'William Shakespeare',
    option4: 'Jane Austen',
    answer: 'William Shakespeare',
  },
  {
    id: 5,
    question: 'Which country is known as the Land of the Rising Sun?',
    option1: 'China',
    option2: 'Japan',
    option3: 'India',
    option4: 'South Korea',
    answer: 'Japan',
  },
  {
    id: 6,
    question: 'What is the smallest prime number?',
    option1: '1',
    option2: '2',
    option3: '3',
    option4: '5',
    answer: '2',
  },
  {
    id: 7,
    question: 'Which ocean is the largest?',
    option1: 'Atlantic Ocean',
    option2: 'Indian Ocean',
    option3: 'Pacific Ocean',
    option4: 'Arctic Ocean',
    answer: 'Pacific Ocean',
  },
  {
    id: 8,
    question: 'What is the boiling point of water at sea level?',
    option1: '90°C',
    option2: '95°C',
    option3: '100°C',
    option4: '105°C',
    answer: '100°C',
  },
  {
    id: 9,
    question: 'Which continent is the Sahara Desert located in?',
    option1: 'Asia',
    option2: 'Africa',
    option3: 'Australia',
    option4: 'South America',
    answer: 'Africa',
  },
  {
    id: 10,
    question: 'Which organ is primarily responsible for pumping blood?',
    option1: 'Brain',
    option2: 'Lungs',
    option3: 'Liver',
    option4: 'Heart',
    answer: 'Heart',
  },
  {
    id: 11,
    question: 'Who was the first man to walk on the moon?',
    option1: 'Buzz Aldrin',
    option2: 'Neil Armstrong',
    option3: 'Yuri Gagarin',
    option4: 'Michael Collins',
    answer: 'Neil Armstrong',
  },
  {
    id: 12,
    question: 'Which gas do plants absorb from the atmosphere?',
    option1: 'Oxygen',
    option2: 'Carbon Dioxide',
    option3: 'Nitrogen',
    option4: 'Helium',
    answer: 'Carbon Dioxide',
  },
  {
    id: 13,
    question: 'What is the largest mammal in the world?',
    option1: 'Elephant',
    option2: 'Blue Whale',
    option3: 'Giraffe',
    option4: 'Rhino',
    answer: 'Blue Whale',
  },
  {
    id: 14,
    question: 'Which language has the most native speakers?',
    option1: 'English',
    option2: 'Spanish',
    option3: 'Mandarin',
    option4: 'Hindi',
    answer: 'Mandarin',
  },
  {
    id: 15,
    question: 'What is the hardest natural substance on Earth?',
    option1: 'Gold',
    option2: 'Iron',
    option3: 'Diamond',
    option4: 'Platinum',
    answer: 'Diamond',
  },
  {
    id: 16,
    question: 'Which planet is known as the Red Planet?',
    option1: 'Earth',
    option2: 'Mars',
    option3: 'Venus',
    option4: 'Mercury',
    answer: 'Mars',
  },
  {
    id: 17,
    question: 'In which country is the Eiffel Tower located?',
    option1: 'Italy',
    option2: 'France',
    option3: 'Germany',
    option4: 'Spain',
    answer: 'France',
  },
  {
    id: 18,
    question: 'Which metal is used to make coins and jewelry?',
    option1: 'Iron',
    option2: 'Copper',
    option3: 'Gold',
    option4: 'Aluminum',
    answer: 'Gold',
  },
  {
    id: 19,
    question: 'Which element is found in table salt?',
    option1: 'Sodium',
    option2: 'Chlorine',
    option3: 'Sodium Chloride',
    option4: 'Potassium',
    answer: 'Sodium Chloride',
  },
  {
    id: 20,
    question: 'Which is the tallest mountain in the world?',
    option1: 'K2',
    option2: 'Mount Everest',
    option3: 'Kangchenjunga',
    option4: 'Lhotse',
    answer: 'Mount Everest',
  },
];
